# Generated by Django 5.0.1 on 2024-01-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(path='uploads/')),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
