# Generated by Django 5.0.1 on 2024-01-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataCleaning', '0002_alter_uploadedfile_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file_path',
            new_name='file',
        ),
    ]
