# Generated by Django 5.0.1 on 2024-01-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCleaning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
